name: Refresh
on:
  push:
  schedule:
    - cron: "0 10 * * *"
  workflow_dispatch:
jobs:
  run:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Push
        run: |
          git config user.name ckt1031
          git config user.email ckt1031@users.noreply.github.com   
          git checkout --orphan latest_branch
          git add -A
          git commit -am "Cập nhật $(date +%F)"
          git branch -D main
          git branch -m main
          git push -f origin main
          
